## Panda

 ### What is Pandas?
Pandas is a Python library used for data analysis and manipulation, providing powerful data structures like Series and DataFrame to handle structured data efficiently.

👉 It is mainly used to:

- Read data (CSV, Excel, JSON, etc.)

- Clean data (remove errors, missing values)

- Analyze data (filter, group, calculate)

- Transform data into useful formats

### Why Pandas is Used?
Without Pandas, handling large datasets in Python is difficult.

With Pandas, you can:

- Work with thousands/millions of rows easily

- Perform operations in just one line of code

- Save a lot of time in data analysis

### Series
A Series in Pandas is a one-dimensional labeled array capable of holding data of any type, where each value is associated with an index.

👉 You can think of it like:

A single column of a table

Or a Python list with labels (index)

In [3]:
import numpy as np
import pandas as pd

In [3]:
labels = ['a', 'b', 'c']
my_list = [10, 20, 30]
arr = np.array([10, 20, 30])
d = {1:10, 2:20, 3:30}

In [7]:
# Create series using list
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [6]:
# Create Series with label
pd.Series(my_list, index=labels)

a    10
b    20
c    30
dtype: int64

In [8]:
# Create Series using array
pd.Series(arr, index=labels)

a    10
b    20
c    30
dtype: int64

In [10]:
# Create Series using dictionary
pd.Series(d)

1    10
2    20
3    30
dtype: int64

### DataFrame
A DataFrame in Pandas is a two-dimensional labeled data structure with rows and columns, capable of storing different types of data.

#### Creating a DataFrame

In [8]:
data = {
    "Name": ["Vinod", "Rahul", "Amit", "Neha", "Priya", "Karan", "Anjali", "Rohit", "Sneha", "Arjun"],
    "Age": [22, 25, 23, 21, 24, 26, 22, 27, 23, 25],
    "Marks": [80, 90, 85, 88, 92, 75, 89, 95, 84, 91],
    "City": ["Delhi", "Mumbai", "Pune", "Bhopal", "Indore", "Chennai", "Jaipur", "Hyderabad", "Lucknow", "Kolkata"],
    "Course": ["BCA", "MCA", "BTech", "BSc", "MCA", "BTech", "BCA", "MCA", "BSc", "BTech"],
    "Passed": [True, True, True, True, True, False, True, True, True, True],
    "Attendance": [85, 90, 88, 92, 95, 70, 89, 96, 87, 93]
}
df1 = pd.DataFrame(data)
df1

     Name  Age  Marks       City Course  Passed  Attendance
0   Vinod   22     80      Delhi    BCA    True          85
1   Rahul   25     90     Mumbai    MCA    True          90
2    Amit   23     85       Pune  BTech    True          88
3    Neha   21     88     Bhopal    BSc    True          92
4   Priya   24     92     Indore    MCA    True          95
5   Karan   26     75    Chennai  BTech   False          70
6  Anjali   22     89     Jaipur    BCA    True          89
7   Rohit   27     95  Hyderabad    MCA    True          96
8   Sneha   23     84    Lucknow    BSc    True          87
9   Arjun   25     91    Kolkata  BTech    True          93

In [4]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
columns = ["Name","Age","City","Salary"]
df2 = pd.DataFrame(data_list,columns =columns)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

#### Selection and Indexing of Column

In [16]:
df1['Name']

0     Vinod
1     Rahul
2      Amit
3      Neha
4     Priya
5     Karan
6    Anjali
7     Rohit
8     Sneha
9     Arjun
Name: Name, dtype: object

#### Select Multiple Columns

In [18]:
df1[['Age', 'City']]

   Age       City
0   22      Delhi
1   25     Mumbai
2   23       Pune
3   21     Bhopal
4   24     Indore
5   26    Chennai
6   22     Jaipur
7   27  Hyderabad
8   23    Lucknow
9   25    Kolkata

#### Select Row

- .loc	Row label + Column name

- .iloc	Row index + Column index

In [10]:
df1.loc[0, "Age"]

np.int64(22)

In [11]:
df1.iloc[0, 1]

np.int64(22)

#### Selecting Row and Column both

In [12]:
df1.iloc[[5, 6, 7]][["Name", "Age", "Marks"]]

     Name  Age  Marks
5   Karan   26     75
6  Anjali   22     89
7   Rohit   27     95

#### Conditional Selection

In [15]:
# I only want to see those people whose age is above 24
df1[df1["Age"] > 24]

    Name  Age  Marks       City Course  Passed  Attendance
1  Rahul   25     90     Mumbai    MCA    True          90
5  Karan   26     75    Chennai  BTech   False          70
7  Rohit   27     95  Hyderabad    MCA    True          96
9  Arjun   25     91    Kolkata  BTech    True          93

In [16]:
# I only want to see those people whose age is above 24 and their city must be Mumbai
df1[(df1["Age"] > 24) & (df1["City"] == "Mumbai")]

    Name  Age  Marks    City Course  Passed  Attendance
1  Rahul   25     90  Mumbai    MCA    True          90

#### Creating a new Column

In [5]:

df2["Designation"] = ['Doctor', 'Eng.', 'Doctor', 'Eng.']
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000        Eng.

#### Removing Column

In [6]:
# Inplace delete data from original dataset
df2 = df2.drop('Designation', axis=1, inplace = True) 
df2

### Removing Missing Data
In real datasets, you often find missing values like:

NaN (Not a Number)

None

👉 Pandas provides functions to remove or handle these missing values easily.

In [27]:
import pandas as pd
import numpy as np

data = {
    "Name": ["Vinod", "Rahul", "Amit", "Neha"],
    "Marks": [80, np.nan, 85, np.nan],
    "Age": [22, 25, np.nan, np.nan]
}

df = pd.DataFrame(data)
print(df)

    Name  Marks   Age
0  Vinod   80.0  22.0
1  Rahul    NaN  25.0
2   Amit   85.0   NaN
3   Neha    NaN   NaN

#### How to Detect Missing Values

In [23]:
df.isnull()      # True where value is missing

    Name  Marks    Age
0  False  False  False
1  False   True  False
2  False  False   True
3  False   True  False

In [24]:
df.isnull().sum()  # count missing values column-wise

Name     0
Marks    2
Age      1
dtype: int64

In [25]:
df.isnull().any()

Name     False
Marks     True
Age       True
dtype: bool

In [19]:
# Drop Rows with Missing Values
df.dropna()

    Name  Marks   Age
0  Vinod   80.0  22.0

In [20]:
# Drop Columns with Missing Values
df.dropna(axis=1)

    Name
0  Vinod
1  Rahul
2   Amit
3   Neha

In [ ]:
# Drop Only Specific Columns
df.dropna(subset=["Marks"])

In [21]:
# Drop Rows with All Missing Values
df.dropna(how="all")

# Removes rows only if all values are NaN

    Name  Marks   Age
0  Vinod   80.0  22.0
1  Rahul    NaN  25.0
2   Amit   85.0   NaN
3   Neha    NaN  21.0

In [28]:
# Use Threshold
# Keep rows with at least 2 non-null values
df.dropna(thresh=2)

    Name  Marks   Age
0  Vinod   80.0  22.0
1  Rahul    NaN  25.0
2   Amit   85.0   NaN

In [29]:
# Filling NaN
df.fillna(200)

    Name  Marks    Age
0  Vinod   80.0   22.0
1  Rahul  200.0   25.0
2   Amit   85.0  200.0
3   Neha  200.0  200.0

In [30]:
# fill different value on different column
values = {'Marks': 70, 'Age': 20}
df.fillna(value=values)

    Name  Marks   Age
0  Vinod   80.0  22.0
1  Rahul   70.0  25.0
2   Amit   85.0  20.0
3   Neha   70.0  20.0

### Merging

Merging means combining two DataFrames based on a common column

In [33]:
import pandas as pd

# DataFrame 1
df1 = pd.DataFrame({
    "ID": [1, 2, 3],
    "Name": ["Vinod", "Rahul", "Amit"]
})

# DataFrame 2
df2 = pd.DataFrame({
    "ID": [1, 2, 4],
    "Marks": [80, 90, 85]
})
pd.merge(df1, df2, on="ID")

   ID   Name  Marks
0   1  Vinod     80
1   2  Rahul     90

#### Types of Merge

In [35]:
# Inner Join (Default)
# Only matching data (common IDs)
pd.merge(df1, df2, on="ID", how="inner")

   ID   Name  Marks
0   1  Vinod     80
1   2  Rahul     90

In [37]:
# Left Join
# All data from left (df1)
pd.merge(df1, df2, on="ID", how="left")

   ID   Name  Marks
0   1  Vinod   80.0
1   2  Rahul   90.0
2   3   Amit    NaN

In [38]:
# Right Join
# All data from right (df2)
pd.merge(df1, df2, on="ID", how="right")

   ID   Name  Marks
0   1  Vinod     80
1   2  Rahul     90
2   4    NaN     85

In [39]:
# Outer Join
# All data from both (union)
pd.merge(df1, df2, on="ID", how="outer")

   ID   Name  Marks
0   1  Vinod   80.0
1   2  Rahul   90.0
2   3   Amit    NaN
3   4    NaN   85.0

In [41]:
# Merge on Different Column Names
# Used when column names are different
pd.merge(df1, df2, left_on="ID", right_on="ID")

   ID   Name  Marks
0   1  Vinod     80
1   2  Rahul     90

### Concatenate

In [43]:
import pandas as pd

df1 = pd.DataFrame({
    "Name": ["Vinod", "Rahul"],
    "Marks": [80, 90]
})

df2 = pd.DataFrame({
    "Name": ["Amit", "Neha"],
    "Marks": [85, 88]
})

In [44]:
# Row-wise Concatenation
pd.concat([df1, df2])

    Name  Marks
0  Vinod     80
1  Rahul     90
0   Amit     85
1   Neha     88

In [45]:
# Column-wise Concatenation
pd.concat([df1, df2], axis=1)

    Name  Marks  Name  Marks
0  Vinod     80  Amit     85
1  Rahul     90  Neha     88

In [46]:
# df.join()
import pandas as pd

df1 = pd.DataFrame({
    "Name": ["Vinod", "Rahul", "Amit"]
}, index=[1, 2, 3])

df2 = pd.DataFrame({
    "Marks": [80, 90, 85]
}, index=[1, 2, 4])

result = df1.join(df2)
print(result)

    Name  Marks
1  Vinod   80.0
2  Rahul   90.0
3   Amit    NaN

### Join Types

In [47]:
# Left Join (Default)
df1.join(df2, how="left")

    Name  Marks
1  Vinod   80.0
2  Rahul   90.0
3   Amit    NaN

In [48]:
# Right Join
df1.join(df2, how="right")

    Name  Marks
1  Vinod     80
2  Rahul     90
4    NaN     85

In [49]:
# Inner Join
df1.join(df2, how="inner")

    Name  Marks
1  Vinod     80
2  Rahul     90

In [50]:
# Outer Join
df1.join(df2, how="outer")

    Name  Marks
1  Vinod   80.0
2  Rahul   90.0
3   Amit    NaN
4    NaN   85.0

### Difference between Concate and join

| Feature  | `concat()`                    | `join()`                  |
| -------- | ----------------------------- | ------------------------- |
| Purpose  | Attach DataFrames             | Combine using index       |
| Logic    | Stacking (no relation needed) | Matching (based on index) |
| Axis     | Row or Column                 | Mostly column-wise        |
| Use Case | Add rows/columns              | Combine related data      |

### GroupBy in Pandas
GroupBy in Pandas is used to split data into groups based on one or more columns and apply aggregation functions like sum, mean, or count.

In [72]:
import pandas as pd

data = {
    "Name": ["Vinod", "Rahul", "Amit", "Neha", "Priya"],
    "Course": ["BCA", "MCA", "BCA", "MCA", "BCA"],
    "Marks": [80, 90, 85, 88, 92]
}

df = pd.DataFrame(data)
df

    Name Course  Marks
0  Vinod    BCA     80
1  Rahul    MCA     90
2   Amit    BCA     85
3   Neha    MCA     88
4  Priya    BCA     92

In [56]:
# Basic GroupBy
df.groupby("Course")

In [57]:
# GroupBy with Aggregation
# Average Marks per Course
df.groupby("Course")["Marks"].mean()

Course
BCA    85.666667
MCA    89.000000
Name: Marks, dtype: float64

In [58]:
# Total Marks per Course
df.groupby("Course")["Marks"].sum()

Course
BCA    257
MCA    178
Name: Marks, dtype: int64

In [59]:
# Count Students per Course
df.groupby("Course")["Name"].count()

Course
BCA    3
MCA    2
Name: Name, dtype: int64

In [60]:
# Multiple Aggregations
df.groupby("Course")["Marks"].agg(["mean", "max", "min"])

             mean  max  min
Course
BCA     85.666667   92   80
MCA     89.000000   90   88

In [61]:
# Group by Multiple Columns
df.groupby(["Course", "Name"])["Marks"].sum()

Course  Name
BCA     Amit     85
        Priya    92
        Vinod    80
MCA     Neha     88
        Rahul    90
Name: Marks, dtype: int64

In [62]:
# Reset Index
df.groupby("Course")["Marks"].mean().reset_index()

  Course      Marks
0    BCA  85.666667
1    MCA  89.000000

### Aggregation in Pandas
Aggregation in Pandas is the process of applying functions like sum, mean, count, min, and max to summarize data.

In [66]:
import pandas as pd

data = {
    "Name": ["Vinod", "Rahul", "Amit", "Neha"],
    "Marks": [80, 90, 85, 88],
    "Age": [22, 25, 23, 21]
}

df = pd.DataFrame(data)

In [67]:
# Basic Aggregation
df["Marks"].sum()
df["Marks"].mean()
df["Marks"].max()
df["Marks"].min()

80

In [68]:
# Aggregation on Multiple Columns
df[["Marks", "Age"]].mean()

Marks    85.75
Age      22.75
dtype: float64

In [69]:
# Using agg() (Very Important 🔥)
df["Marks"].agg(["sum", "mean", "max"])

sum     343.00
mean     85.75
max      90.00
Name: Marks, dtype: float64

In [70]:
# Aggregation with GroupBy
df.groupby("Name")["Marks"].sum()

Name
Amit     85
Neha     88
Rahul    90
Vinod    80
Name: Marks, dtype: int64

In [73]:
# Multiple Aggregations with GroupBy
df.groupby("Course")["Marks"].agg(["mean", "max", "min"])

             mean  max  min
Course
BCA     85.666667   92   80
MCA     89.000000   90   88

### Pivot Table
A Pivot Table in Pandas is used to summarize data by grouping values and applying aggregation functions to create a structured table.

In [2]:
import numpy as np 
import pandas as pd

In [15]:
import pandas as pd

data = {
    "Name": ["Vinod", "Rahul", "Amit", "Neha", "Priya"],
    "Course": ["BCA", "MCA", "BCA", "MCA", "BCA"],
    "Marks": [80, 90, 85, 88, 92],
    "City": ["Delhi", "Mumbai", "Delhi", "Mumbai", "Delhi"]
}

df = pd.DataFrame(data)
df

    Name Course  Marks    City
0  Vinod    BCA     80   Delhi
1  Rahul    MCA     90  Mumbai
2   Amit    BCA     85   Delhi
3   Neha    MCA     88  Mumbai
4  Priya    BCA     92   Delhi

In [16]:
# Basic Pivot Table
pd.pivot_table(df, values="Marks", index="Course")

            Marks
Course
BCA     85.666667
MCA     89.000000

In [17]:
# Multiple Columns
pd.pivot_table(df, values="Marks", index="Course", columns="City")

City        Delhi  Mumbai
Course
BCA     85.666667     NaN
MCA           NaN    89.0

In [11]:
# Using Different Aggregation Functions
pd.pivot_table(df, values="Marks", index="Course", aggfunc="sum")

        Marks
Course
BCA       257
MCA       178

In [12]:
# Multiple Aggregations
pd.pivot_table(df, values="Marks", index="Course", aggfunc=["mean", "max"])

             mean   max
            Marks Marks
Course
BCA     85.666667    92
MCA     89.000000    90

In [13]:
# Fill Missing Values
pd.pivot_table(df, values="Marks", index="Course", columns="City", fill_value=0)

City        Delhi  Mumbai
Course
BCA     85.666667     0.0
MCA      0.000000    89.0

In [14]:
# Count Example
pd.pivot_table(df, values="Name", index="Course", aggfunc="count")

        Name
Course
BCA        3
MCA        2

### Operations

In [19]:
df3 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})
df3

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [21]:
df3.shape

(5, 3)

In [22]:
df3.columns

Index(['A', 'B', 'C'], dtype='object')

In [23]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [24]:
df3.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [27]:
df3['D'] = df3["B"].apply(lambda x : x**2)
df3

   A   B    C     D
0  1  10  100   100
1  2  20  200   400
2  3  30  300   900
3  4  40  400  1600
4  5  50  500  2500